### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by matthew42904** [nzin/dctycoon#34]
dose docker work?

**Comment by nzin** [comment]
Hi @matthew42904 , I dont remember if I created the Dockerfile, only for QA purpose (see if it compiles, and send metrics to Code Climate).
What are you trying to achieve? on which OS are you?

Regards,

**Comment by nzin** [comment]
I pushed a new commit to update to go 1.18.
But really the dockerfile is mostly there for QA/code climate

**Comment by matthew42904** [comment]
I was going to put it on my server which runs unraid
